### ISSUE TITLE
Make it easier to jump to top/bottom of tasks

### ISSUE THREAD

**Issue by khughitt** [kdheepak/taskwarrior-tui#42] opened 2020-11-03 18:25 UTC
**Description**

Currently, to navigate to the top/bottom of the task list one has to use the arrow, j/k, or page up/down keys to move up or down, being careful to stop at the first/last entry.

If one goes too fast, however, it's very easy to miss the desired entry at which point the tui cycles to the other end of the tasks and continues.

**Solution**

A couple possible solutions:

1. Add option to prevent taskwarrior from "looping" (i.e. when you get to the first entry, pressing the up arrow again has no effect, and vice versa for the last entry).
2. Add support for vim key bindings used to jump to the start/end of a page:
  - `gg`    go to top
  - `shift-g`   go to bottom

Thanks for your work on this great tool!

Cheers,
Keith

**Comment by kdheepak** [comment] 2020-11-03 18:37
Great idea! That's on my TODO list as well! Currently, I don't have a good way to handle a key press followed quickly by a key press (i.e. for `gg`). I was toying with the idea of using `HOME` and `END` for moving to the top and bottom. Other suggestions are welcome. 

`gg` and `G` would be ideal though, since vim users already have that muscle memory. This might happen when I refactor the code.

For now, pressing `J` and `K` will get you moving a page down and a page up respectively. And adding an option to disable looping is a great idea! I'll do that.

**Comment by khughitt** [comment] 2020-11-03 19:21
That sounds good to me! Vim conventions would be cool to have in the long run, but definitely not urgent. Simply having an option to disable the looping would be great for the time being.

Thanks for the quick response!

**Closed** 2020-11-03 19:49 UTC
Labels: enhancement

**Comment by kdheepak** [comment] 2020-11-03 20:14
This has been implemented! You can get it in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.9.1. 

I've had some somewhat odd behavior with `gg` though, it's almost like the event gets swallowed sometimes (I was able to trigger this behavior 1 in 10 attempts). The alternative is to just use `g` to move to the top. If you are able to reproduce this as well, I'll revert to just supporting `g` instead of `gg` for moving to the top.

**Comment by khughitt** [comment] 2020-11-03 21:43
Okay awesome! I'll give it a shot and let you know if I get similar behavior.

Thanks for the quick fix!

**Comment by khughitt** [comment] 2020-11-03 21:57
Okay I gave it a shot and overall it works great.

I am running into the same issue with `gg`; in my case it seems to drop about 20% of the time, and does not depend on the position or timing of the key presses.

I took a quick look at the code, but unfortunately I'm not too familiar with Rust and nothing stuck out as being problematic.

It could be worth asking about on S/O or some other Rust community in case someone more knowledgeable has an idea what the problem could be, but I'm also completely fine with just having `g` serve as the shortcut since it is not being used for anything else anyway.

Thanks again!

**Comment by kdheepak** [comment] 2020-11-03 22:27
Thanks for testing! I've reverted it in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.9.2. I'll ask on SO or /r/rust once I'm able to produce a minimal working example.

**Comment by kdheepak** [comment] 2020-11-03 23:55
I'm pretty sure I resolved it! You can find the `gg` feature in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.9.3. Please feel free to post here or open a new issue if you run into other issues.

**Comment by khughitt** [comment] 2020-11-04 23:56
Awesome! I will give it a shot and let you know if I encounter any more strange issues. Thanks for following up!
