### ISSUE TITLE
Failed to run (parsing `task data.location` failed)

### ISSUE THREAD

**Issue by j3k0** [kdheepak/taskwarrior-tui#174] opened 2021-04-05 08:51 UTC
**Describe the bug**

```
$ RUST_BACKTRACE=full ./taskwarrior-tui
Backtrace (most recent call first):
  File "<unknown>", line 0, in __libc_start_main

The application panicked (crashed).
  called `Result::unwrap()` on an `Err` value: Unable to parse `task show data.location`.
in src/config.rs, line 345
thread: main
```

**Environment**

- Operating System: Linux
- Installation: github releases
- taskwarrior-tui version: 0.13.6
- task version: 2.5.1

**Additional context and information**

```
$ task show data.location

Config Variable Value
data.location   ~/me/taskwarrior
  Default value ~/.task

Some of your .taskrc variables differ from the default values.
  These are highlighted in color above.
```

**Comment by kdheepak** [comment] 2021-04-05 13:23
Huh, that’s surprising. I use this everyday. Can you share the part of your `.taskrc` where you set the location? Or if you set it using environment variables can you share that? 

If you are able to replicate it using this repo, that’ll help narrow down the problem:
https://github.com/kdheepak/taskwarrior-testdata

**Comment by kdheepak** [comment] 2021-04-05 16:58
I tried different settings in my local configuration and I was not able to replicate this.

1) I added `data.location=~/gitrepos/taskwarrior-tui/tests/data/.task` to `~/.taskrc`
2) I added the following environment variables to my configuration:

```
export TASKRC=`pwd`/tests/data/.taskrc
export TASKDATA=`pwd`/tests/data/.task
```

Both worked fine for me. So we'll need more information from you to figure out what is going on here.

**Comment by ipwnponies** [comment] 2021-07-31 17:20
I ran into this issue as well. It turned out to `rc._forcecolor` config set to 'yes' interferes with this.

https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/doc/man/taskrc.5.in#L435-L451
> Taskwarrior shuts off color automatically when the output is not sent directly
to a TTY.

I don't remember setting this, it might be default auto-generated config or maybe it's to use another color theme. The default is 'no'.

It's definitely a misleading error message in my case, has nothing to do with the data location at all:

```
$ taskwarrior-tui

Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  called `Result::unwrap()` on an `Err` value: Unable to parse `task show data.location`.
in src/config.rs, line 409
thread: main
```

**Comment by kdheepak** [comment] 2021-09-05 06:12
I'm still unable to reproduce this, even if I set `rc._forcecolor=on` in my `.taskrc`, I don't get this error. 

@ipwnponies Are you able to consistently reproduce this? Can you share the output of your `task show data.location`?

**Comment by ipwnponies** [comment] 2021-09-07 18:44
@kdheepak huh, I can no longer reproduce this. It was definitely reproducing consistently. Perhaps something transient in that shell environment was contributing to this.

Here's the context of my setup:
* Operating System: macOS catalina (10.15)
* Installation: brew
* taskwarrior-tui version: 0.13.29
* task version: 2.5.3


```
$ task show data.location
Config Variable Value
data.location   ~/Google Drive/TaskWarrior/
  Default value ~/.task

Some of your .taskrc variables differ from the default values.
  These are highlighted in color above.
```

Unfortunately I could not recover the exact `.taskrc` (not version controlled), in case it's a bug to do with `.taskrc` parsing implementation. 😞

**Comment by kdheepak** [comment] 2021-09-07 18:54
So strange! I’ll close this issue for now. If someone else reports or produces a reproducible example, I’ll reopen. I’ve never been able to reproduce this so I don’t have any idea what could be going on, so I don’t know what change I even could make now to improve this.

**Comment by kdheepak** [comment] 2021-09-07 18:55
The only thing I imagine could be happening is perhaps an older version of `task` doesn’t report data location the way I’m expecting it too. In that case one would need to update to the latest version.

**Closed** 2021-09-07 18:55 UTC
Labels: bug
