### ISSUE TITLE
Cursor jumping ahead on edit lines when multibyte characters are entered

### ISSUE THREAD

**Issue by RauchF** [kdheepak/taskwarrior-tui#49] opened 2020-11-09 13:37 UTC
**On entering multibyte characters in line-inputs, like when entering a task title, the cursor has some spacing issues**

**To Reproduce**

- Start taskwarrior-tui
- Press `a` to enter add mode
- Enter a title containing multibyte characters such as `äéíß` etc
- With each entered multibyte char, the cursor jumps one space further ahead.
- When deleting the characters via `backspace`, the spacing is correct again.

![image](https://user-images.githubusercontent.com/7746494/98547553-a5fb1100-2298-11eb-89bd-aae5469d775d.png)

**Environment:**

- Operating System: Linux 5.8.17 (Fedora Workstation 33), using Konsole 20.08.1 as terminal emulator, bash as shell, `en_US.UTF8` as system locale.
- Installation: `cargo build` from fresh GitHub repo clone
- taskwarrior-tui version: `0.9.3` / latest `master`
- task version: 2.5.1

**Comment by kdheepak** [comment] 2020-11-09 14:02
Thanks for reporting. This should be a fairly easy fix :) I'll look into it today. 

The issue is I'm using `s.len()` or `s.chars().len()` when I think I should be using `s.graphemes().len()`.

**Comment by kdheepak** [comment] 2020-11-09 17:41
Can you try the latest commit on `master`? This should be fixed now. If it works for you as expected, I'll make a new release.

**Closed** 2020-11-09 17:40 UTC
Labels: bug

**Comment by RauchF** [comment] 2020-11-10 10:06
Looks good! :+1: 
![image](https://user-images.githubusercontent.com/7746494/98659712-b4066b80-2344-11eb-86f9-e439e0212d73.png)
Thank you for the quick fix :)
