### ISSUE TITLE
taskwarrior-tui crashes when returning from hibernation after a long time

### ISSUE THREAD

**Issue by desbma** [kdheepak/taskwarrior-tui#233] opened 2021-06-07 09:25 UTC
`taskwarrior-tui` crashes when returning from hibernation after a long time.
I think it is reproducible only if I hibernate for more than 24hours, but I am not 100% sure.

I have this bug since a long time, but I finally managed to reproduce it with `RUST_BACKTRACE=full`:

```
$ RUST_BACKTRACE=full taskwarrior-tui
Backtrace (most recent call first):
  File "rust:library/core/src/option.rs", line 1300, in core::option::expect_none_failed
  File "rust:library/core/src/result.rs", line 997, in core::result::Result<T,E>::expect
  File "/home/mde/build/taskwarrior-tui/src/main.rs", line 62, in taskwarrior_tui::main
    task::block_on(tui_main(config, report)).expect(
  File "rust:library/core/src/ops/function.rs", line 227, in core::ops::function::FnOnce::call_once
  File "rust:library/std/src/sys_common/backtrace.rs", line 125, in std::sys_common::backtrace::__rust_begin_short_backtrace

The application panicked (crashed).
  [taskwarrior-tui error]. If you need additional help, please report as a github issue on https://github.com/kdheepak/taskwarrior-tui: second time provided was later than self
in src/main.rs, line 62
```

**Environment (please complete the following information):**

- Operating System: Debian Sid
- Installation: from source
- taskwarrior-tui version: `0.13.22`

**Comment by kdheepak** [comment] 2021-06-07 13:03
Thanks for reporting. Does it crash without you doing anything or does it crash after you wait a while and then when you come back to it and press a keystroke? I’m assuming the former but wanted to check.

**Comment by desbma** [comment] 2021-06-07 13:07
Without doing anything: after returning from hibernation, when I focused the terminal I saw it crashed.

**Comment by kdheepak** [comment] 2021-06-07 13:12
> when I focused the terminal

Interesting. I’ll see if I can replicate this. There is a chance this will depend on operating system or terminal emulator (not because I think that’s the case but because I have no idea what is going on). There’s a tick rate configuration option that you can try to use and see if you can replicate it faster.

**Comment by desbma** [comment] 2021-06-07 13:18
To clarify: I saw that it crashed when I focused the terminal, but it probably has crashed before that.

**Comment by kdheepak** [comment] 2021-06-07 13:38
Ah okay! I’m not a native English speaker too! Thanks for clarifying! I was thinking that if it crashed on focus there’s a chance it is operating system / terminal emulator specific. Now I think it is less likely. I’ll try to reproduce it and let you know if I can or cannot. My work machine goes to sleep quite quickly if I don’t use it so I’ll have to try it on another machine.

**Comment by kdheepak** [comment] 2021-06-07 18:08
I think the PR will fix it but I haven’t tested it. I haven’t been able to replicate the error even with a faster tick rate. Let me know if you get a chance to try it over a day or two.

**Comment by desbma** [comment] 2021-06-07 21:37
I'll tell you next week, since it happens on my work laptop and I only hibernate more than 24hours during the week end.

**Comment by desbma** [comment] 2021-06-14 10:21
I confirm this code was the cause of the crash and your fix solves it.
However since I am the author of that bug, I feel guilty and suggest another approach to fix it.

**Comment by desbma** [comment] 2021-06-22 09:33
I am now getting this error randomly when returning from hibernation.
    
    RUST_BACKTRACE=full taskwarrior-tui
    [taskwarrior-tui error]: second time provided was later than self
    
    If you need additional help, please report as a github issue on https://github.com/kdheepak/taskwarrior-tui

I think it's due to this line https://github.com/kdheepak/taskwarrior-tui/blob/9b75491f6edd550499f4efb275e46e19c3aaf6b8/src/app.rs#L1352
I'll make a PR soon tof ix it.

**Comment by kdheepak** [comment] 2021-06-22 12:57
We can also change it such that the `update` method shouldn’t error and crash, if you are not able to find a fix for this.

**Comment by desbma** [comment] 2021-06-22 21:45
> We can also change it such that the update method shouldn’t error and crash

I did exactly that. This is more robust, because `SystemTime` is not monotonic and unlike `Instant`, it can move backwards. I don't understand why that happens with hibernation, but that should fix it anyway.

**Closed** 2021-06-22 22:36 UTC
Labels: bug

**Comment by kdheepak** [comment] 2021-07-19 19:34
Thanks for making the PR for this change. I've made a new release with this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.25
