### ISSUE TITLE
Perform an operation on multiple tasks

### ISSUE THREAD

**Issue by nickwynja** [kdheepak/taskwarrior-tui#139] opened 2021-03-17 15:03 UTC
**Description**

Often when I'm processing many tasks, like sorting through an "inbox" context, I want to select multiple tasks and perform the same operation on them. For example, I might have several tasks without a project and I'd like to 'mark' several as selected and then add `pro:work` to each of them. It's currently very repetitive to process several similar tasks.

**Solution**

I think something similar to the [way mutt handles 'tags'](http://www.mutt.org/doc/manual/manual.html#tags) would work well here. Basically you mark (tag in mutt's terms) each item you want to select and then can run an operation on each.

**Additional context**

I'm sure this is a bit more complicated than it sounds due to things like displaying errors for each task depending on its success.

**Comment by kdheepak** [comment] 2021-03-18 12:08
This is a great idea!

I’ve also currently found that the biggest pain point when using taskwarrior-tui is performing multiple operations. I’ve ended up leaving the tui open and opening a different terminal and typing in the command line `task id1 id2 id3 mod ...`. Ideally I would never have to do anything outside the tui. 

I think implementing the selection of multiple tasks is probably straightforward. I’m also experimenting with history and a form of autocomplete. That, with user defined shortcuts should solve a lot of problems.

**Comment by kdheepak** [comment] 2021-03-23 21:08
@nickwynja I have a first prototype PR for multiple selection. I was wondering if you'll be able to give it a test.

You can press `v` to enter "selection" mode. Hitting `v` again toggles selection on the currently highlighted task. Hitting `Esc` exits "selection" mode and clears the selection. In "selection" mode, all existing functionality will work as before. The only difference is that "modify", "annotate" and "shortcuts" will work on all selected tasks. 

Any feedback ranging from "this sequence of inputs causes a bug" to "the UI is not intuitive" is welcome :)

**Comment by kdheepak** [comment] 2021-03-23 22:57
I'll plan to use it for a few days, and see if any bugs fall out of daily driving it.

**Comment by nickwynja** [comment] 2021-03-24 00:28
This is awesome and very exciting! Playing around a bit and here's a few things that came up:

- I like how it says `Modify Tasks 41,17,39` when you are making a change. Very clear what's going to happen
- If I make a change like adding a project which changes the urgency of a task and reorders the list, the `[x]` selections stay in the list position they were and not with the task id that was selected. This seems like a bug.
- My initial attempt was to select several items and then hit `d` to mark them as done. This marked the current (bold) item as done and didn't effect the `[x]` selected items. This wasn't what I expected would happen. I realize it's extra keystrokes to select and then `d` when I could just `d` each one but sometimes my mind wants to do the "bulk" action rather than the individual actions
- UX-wise, it feels like the mode might not need to be completely separate from the action. For example, I think `v` would switch to selection mode and select the item and `Esc` could still cancel out of the mode but having the selection mode remain active when nothing is selected is unexpected for me. If I hit `v` which switched the mode and selected the item and then I hit `v` again to deselect it, I would expect that tui would automatically leave select mode. 
- I'd also expect tui to automatically leave selection mode after performing an action like modify but this might just be personal preference since I can see a use case where you way want to annotate and then modify the same items without having to reselect
- My mind associated selections with `x` so I hit the `x` shortcut (instead of `v`) more than once to select an item. This deleted the task which makes me think #47 relates to this or maybe delete should have a different default key that isn't so visually similar to the `[x]` of selection

I'll keep playing as well and let you know if anything else comes up. But it's already very useful!

**Comment by nickwynja** [comment] 2021-03-24 00:57
>I'd also expect tui to automatically leave selection mode after performing an action like modify but this might just be personal preference since I can see a use case where you way want to annotate and then modify the same items without having to reselect

Just realized another use case which suggests that selection mode _shouldn't_ reset after an action: executing a custom command on the selected items. When you run a command on multiple items the items stay selected and I don't think there's any good reason to deselect them when, for example, the script comes back with a zero exit code. Therefore keeping selection mode on after an action like `modify` would be consistent with how tui would behave after running on a script.

**Comment by kdheepak** [comment] 2021-03-24 01:06
Thanks for providing such useful feedback! I knew it was the right decision letting you review this early version :) Thanks again for being a test subject.

> If I make a change like adding a project which changes the urgency of a task and reorders the list, the [x] selections stay in the list position they were and not with the task id that was selected. This seems like a bug.

This is a bug. I am tracking the task index, instead of the task IDs. I'll update this.

> My initial attempt was to select several items and then hit d to mark them as done. This marked the current (bold) item as done and didn't effect the [x] selected items. This wasn't what I expected would happen. I realize it's extra keystrokes to select and then d when I could just d each one but sometimes my mind wants to do the "bulk" action rather than the individual actions

I'll be able to support this for `done`, and `delete` too. I'll update the implementation.

> If I hit v which switched the mode and selected the item and then I hit v again to deselect it, I would expect that tui would automatically leave select mode.

I agree with this too. I think that is more intuitive behavior. 

I'll make these changes first, and then share some additional comments based on my testing and the rest of your comments. Thanks again for the extremely useful feedback!

**Comment by kdheepak** [comment] 2021-03-24 02:28
I've updated it to support `done` and `delete` too. 

`task start` and `task stop` is the only thing that isn't supported that in theory could be supported. If a user selects a task that is started and a task that is not started and hits `s`, should the TUI toggle the started task to stop and the stopped task to start? I think that's what I'm leaning toward at the moment.

I've also fixed the `x` not appearing it the correct location after the task list is reordered (for example when the urgency changes). 

However, I'm getting some strange non-deterministic but randomly reproducible hangs at the moment. I'll have to look into this more carefully. For now, I wanted to comment and let you know that you should use this branch with caution! I don't want it such that testing this branch causes you to mess up your task list ( although I'm sure you have backups :) ).

**Comment by kdheepak** [comment] 2021-03-24 04:59
I'm not sure exactly what is going on here but when multiple tasks (all visible tasks for example) are `delete`d or marked as `done`, `taskwarrior-tui` hangs. The actual `delete` or `done` works fine though. I think this has to do with the way I'm drawing the task report. I'm investigating it at the moment.

**Comment by kdheepak** [comment] 2021-03-24 05:37
I fixed the hanging issue (https://github.com/kdheepak/taskwarrior-tui/pull/147/commits/b38979bf024d24077263479bb41f49647fc6bd48) and added support for `start` and `stop` (https://github.com/kdheepak/taskwarrior-tui/pull/147/commits/edd7fc39f18cfd11f226c20929e743da1695d9a9). I also fixed some edge cases, so the interface should behave more "intuitively". Happy to make more changes if you have any other suggestions!

**Comment by kdheepak** [comment] 2021-03-24 05:44
I've also added a `select-all` option that toggles the selection for all tasks in the report. You can access it by pressing `V`, i.e. capital `V`.

**Comment by nickwynja** [comment] 2021-03-24 12:21
Nice updates! This is all feeling really good. I can't think of any more UX or workflow things that are feeling rough around the edges.

One bug I'm seeing now is if I have selections and then hit `Esc`, I see the selection.indicator (which I have customized to ❯) repeated for each item which was selected with an `[x]`. I tried removing my custom selection.indicator to use the default and the issue still occurs.

**Comment by kdheepak** [comment] 2021-03-24 14:48
Nice catch! This is fixed in https://github.com/kdheepak/taskwarrior-tui/pull/147/commits/b098ba11f4f14be092fbbf85a17255efab2b8fcd. The selection indicator should be just one now when you go back to the normal mode.

**Comment by kdheepak** [comment] 2021-03-25 21:19
I think I've tested most of the functionality in my day to day use, and I'm fairly confident the multiple selection is working as intended. I've changed `[x]` to `[✓]` because 1) like you said `[x]` seems to invite pressing `x`, and 2) the check mark `✓` is closer to `v` (if you squint really hard). 

I'll do another pass of testing and maybe write some actual tests but I'm comfortable merging to the `master` branch now. Let me know if you have any feedback as well.

**Comment by kdheepak** [comment] 2021-03-25 21:30
The `☑` is smaller than I'd like but I think I'll make it customizable the way the highlight indicator is set up.

**Comment by nickwynja** [comment] 2021-03-25 22:27
How about ✔ or ✓ as the defaults?

I didn't get enough work done today to thoroughly test it out more but hopefully tomorrow!

**Comment by kdheepak** [comment] 2021-03-25 22:37
I tried `✓` too: https://github.com/kdheepak/taskwarrior-tui/pull/147/commits/a204ec85803dfd127f1f8a0d7084db99fd1dba5b

We basically need two symbols. One for checking a task when we press `v` and another for the remaining items that are unchecked. Previously I was using `[x]` and `[ ]` however that was 3 characters and it requires shifting the table a little. I'd prefer we didn't have to do that. I could use `✓` but didn't find a good character to complement it for the unchecked state. I explored leaving it blank but that didn't convey clearly that the user has "checked" a row. 

As of the most recent commit they are configurable too, if you test it out with any unicode characters to offer suggestions. I'll also look through unicode symbols again to see if I can spot something better.

**Comment by nickwynja** [comment] 2021-03-26 11:51
Personally, I like the simplicity of `*` for mark_indicator and ` ` for unmarked. This is similar to how neomutt shows 'tagged' (marked) items.

![image](https://user-images.githubusercontent.com/1012017/112626934-4b0d2500-8e07-11eb-8f91-d2c43416e125.png)

It's not possible to override `☐` with a uda of ` ` because of the `is_empty()` check. So maybe the default should be blank and if people prefer a different character they can use the uda?

```diff
diff --git a/src/config.rs b/src/config.rs
index 55a2904..33d2522 100644
--- a/src/config.rs
+++ b/src/config.rs
@@ -342,7 +342,7 @@ impl Config {
     fn get_uda_mark_indicator() -> String {
         let indicator = Self::get_config("uda.taskwarrior-tui.mark.indicator");
         if indicator.is_empty() {
-            "☑ ".to_string()
+            "* ".to_string()
         } else {
             format!("{} ", indicator)
         }
@@ -351,7 +351,7 @@ impl Config {
     fn get_uda_unmark_indicator() -> String {
         let indicator = Self::get_config("uda.taskwarrior-tui.unmark.indicator");
         if indicator.is_empty() {
-            "☐ ".to_string()
+            "  ".to_string()
         } else {
             format!("{} ", indicator)
         }
```

**Comment by kdheepak** [comment] 2021-03-26 18:28
Nice catch! The latest commit should allow empty strings as indicators: https://github.com/kdheepak/taskwarrior-tui/pull/147/commits/437b4642ad2fda3b12d3a5253c3435cc63f4851f

**Comment by kdheepak** [comment] 2021-03-27 00:44
I've reverted to using `✔` for marks and the empty string ` ` for unmarks as defaults.

**Comment by kdheepak** [comment] 2021-03-27 01:07
I think the PR is ready to merge. I'll wait for any final feedback from you though once you get the chance, I'm not in a hurry :)

**Comment by kdheepak** [comment] 2021-03-27 20:26
I'm going to merge the PR because I would like to make a few refactoring changes to improve performance. Feel free to post here or open new issues if you find anything you'd like to share as feedback!

**Closed** 2021-03-27 20:27 UTC
Labels: enhancement

**Comment by kdheepak** [comment] 2021-03-31 08:19
This feature is now available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.0.
